### ISSUE TITLE
Mark more then one line

### ISSUE THREAD

**Issue by m3koenig** [thomasrayner/RightLines#3]
Currently there is only one mark possible.
As a Developer, I want to mark several lines manually to focus on these or showing someone else.

(BTW, as a developer I like your Extension :D)

**Comment by thomasrayner** [comment]
Good news! This is fixed with a new setting in v0.0.2. It only took me a year and a half to get to, but thank you for drawing this to my attention, @m3koenig! And thank you for your patience 😅

The new setting is `rightlines.ClearExistingMarksOnSingleMark` and it defaults to `false`, which is the behavior it looks like you prefer.
